import React, { useState, useEffect } from 'react';
import { ChevronLeft, FileText, Check, AlertTriangle } from 'lucide-react';
import { useAppContext } from '@/context/AppContext';
import { useAuth } from '@/hooks/useAuth';
import { View } from '@/types';
import { supabase } from '@/integrations/supabase/client';

interface StatementData {
  id: string;
  original_deposit: number;
  inspection_deductions: number;
  issue_deductions: number;
  final_amount: number;
  status: string;
  created_at: string;
}

const ResidentDepositView: React.FC = () => {
  const { setActiveView } = useAppContext();
  const { user } = useAuth();
  const [statement, setStatement] = useState<StatementData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchStatement();
  }, [user]);

  const fetchStatement = async () => {
    if (!user) return;
    
    // Get profile to find employee_id
    const { data: profile } = await supabase
      .from('profiles')
      .select('employee_id')
      .eq('user_id', user.id)
      .single();

    if (profile?.employee_id) {
      const { data } = await supabase
        .from('security_deposit_statements')
        .select('*')
        .eq('employee_id', profile.employee_id)
        .order('created_at', { ascending: false })
        .limit(1)
        .single();

      if (data) setStatement(data as StatementData);
    }
    setLoading(false);
  };

  const totalDeductions = (statement?.inspection_deductions || 0) + (statement?.issue_deductions || 0);

  return (
    <div className="animate-fade-in">
      <div className="header-gradient text-primary-foreground p-4">
        <div className="flex items-center gap-3">
          <button onClick={() => setActiveView(View.RESIDENT_HOME)}>
            <ChevronLeft className="w-6 h-6" />
          </button>
          <h1 className="text-lg font-bold">My Deposit Statement</h1>
        </div>
      </div>

      <div className="p-4">
        {loading ? (
          <div className="text-center py-12">
            <div className="w-8 h-8 border-2 border-secondary border-t-transparent rounded-full animate-spin mx-auto mb-2" />
            <p className="text-muted-foreground">Loading statement...</p>
          </div>
        ) : !statement ? (
          <div className="text-center py-12">
            <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="font-bold text-foreground mb-2">No Statement Available</h3>
            <p className="text-sm text-muted-foreground">
              Your security deposit statement will appear here once generated by your housing manager.
            </p>
          </div>
        ) : (
          <div className="bg-card rounded-xl p-6 shadow-sm space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-full bg-secondary/10 flex items-center justify-center">
                <FileText className="w-6 h-6 text-secondary" />
              </div>
              <div>
                <h2 className="font-bold text-foreground">Deposit Summary</h2>
                <p className="text-xs text-muted-foreground">
                  Generated {new Date(statement.created_at).toLocaleDateString()}
                </p>
              </div>
            </div>

            <div className="space-y-3">
              <div className="flex justify-between py-2 border-b border-border">
                <span className="text-foreground">Original Deposit</span>
                <span className="font-bold text-foreground">${statement.original_deposit.toFixed(2)}</span>
              </div>

              {(statement.inspection_deductions || 0) > 0 && (
                <div className="flex justify-between py-2 border-b border-border">
                  <span className="text-foreground">Inspection Damages</span>
                  <span className="text-destructive font-bold">-${statement.inspection_deductions?.toFixed(2)}</span>
                </div>
              )}

              {(statement.issue_deductions || 0) > 0 && (
                <div className="flex justify-between py-2 border-b border-border">
                  <span className="text-foreground">Issue Deductions</span>
                  <span className="text-destructive font-bold">-${statement.issue_deductions?.toFixed(2)}</span>
                </div>
              )}

              {totalDeductions === 0 && (
                <div className="py-3 flex items-center gap-2 text-success">
                  <Check className="w-5 h-5" />
                  <span className="font-medium">No deductions — full deposit returned</span>
                </div>
              )}

              <div className="flex justify-between pt-3">
                <span className="text-lg font-bold text-foreground">Amount Due to You</span>
                <span className={`text-2xl font-bold ${statement.final_amount >= 0 ? 'text-success' : 'text-destructive'}`}>
                  ${Math.abs(statement.final_amount).toFixed(2)}
                </span>
              </div>
            </div>

            {totalDeductions > statement.original_deposit * 0.5 && (
              <div className="bg-warning/10 rounded-xl p-3 flex items-start gap-3 mt-4">
                <AlertTriangle className="w-4 h-4 text-warning flex-shrink-0 mt-0.5" />
                <p className="text-sm text-muted-foreground">
                  Deductions exceed 50% of your deposit. Contact your housing manager for details.
                </p>
              </div>
            )}

            <p className="text-center text-xs text-muted-foreground pt-4">
              Statement verified by Be Connect Platform
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default ResidentDepositView;
